name: riomar-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - numpy
  - xarray
  - zarr
  - s3fs
  - h5netcdf
  - cftime
  - nbqa
  - ruff
  - black
  - isort
  - nbconvert
  - pytest
  - pytest-cov
  - jupyter
  - mystmd
  - nodejs=18  # For mystmd CLI
  - pip
  - matplotlib
  - cartopy
  - dask
  - panel
  - hvplot
  - geoviews
  - pip:
      - fs.onedatarestfs
      - healpix-geo
      - git+https://github.com/EOPF-DGGS/healpix-plot.git
